default:
  train:
    fleet_size: 3  # Minimum fleet size greater than 2
    capacity: 100  # Default capacity for each train
    schedule:
      frequency: 10  # Frequency in minutes
      departures: []  # Explicit departure times can be added here
  station:
    transfer_time: 2  # Default transfer time in minutes
  simulation:
    duration: 120  # Total simulation time in minutes
    time_step: 1  # Time step for the simulation in minutes
  passenger:
    default_speed_mps: 1.4  # Default walking speed for passengers in meters per second